// ENERGY / PHONK
const energyPhonk = [
  { title: "Sunny Sunny", file: "music/SunnySunny.mp3" },
  { title: "Against All Odds AP Dhillon", file: "music/AgainstAllOdds.mp3" },
  { title: "Gigachad Theme", file: "music/gigachad.mp3" },
  { title: "Metamorphosis Interworld", file: "music/metamorphosis.mp3" },
  { title: "Sahara Hensonn", file: "music/saharahensonn.mp3" },
  { title: "Crystals Isolate", file: "music/crystalsIsolate.mp3" },
  { title: "Aarambh Prachand X Polezehnie", file: "music/AarambhPrachandPolo.mp3" },
  { title: "Post Malone - rockstar", file: "music/Rockstar-PostMalone.mp3" },
  { title: "Sia - Unstoppable", file: "music/Sia-Unstoppable.mp3" },
  { title: "Ravan Ravan Hoon Main Rock D", file: "music/Ravan-RockD.mp3" },
  { title: "Swaggin' at the Partment - Ghostface Playa", file: "music/Swagin-Playa.mp3" },
  { title: "INVINCIBLE - Sidhu Moose Wala Stefflon Don", file: "music/Invincible-Sidhu.mp3" },
  { title: "Yaar Bathere - Honey Singh x Alfaaz", file: "music/YaarBathere-Honey.mp3" },
  { title: "2Pac - Hit 'Em Up (feat. Outlawz)", file: "music/2PacHitEm.mp3" },
  { title: "Kaleshi Chori", file: "music/KaleshiChori.mp3" },
  { title: "Same Beef Song BOHEMIA Ft. Sidhu Moose Wala", file: "music/SameBeef.mp3" },
  { title: "Wels, PLXYAE - NXSTY BLOOD 2 (2023)", file: "music/NxstyBlood2.mp3" },
  { title: "BENZ - Young Stunners", file: "music/BenzYoung.mp3" },
  { title: "MONTAGEM INVASÃO (Slowed) - ARXMANE", file: "music/MontagemInvasaoSlowed.mp3" },
  { title: "AUTOMOTIVO DA TURBULENCIA - Ultra Slowed", file: "music/AutomativoUSlowed.mp3" },
  { title: "Jatt Mehkma - Honey Singh", file: "music/JattMehkma.mp3" },
  { title: "Khamzat Chimaev Theme Song - Vekisha", file: "music/KhamzatChimaev.mp3" },
  { title: "VEGETA PHONK - gqtis", file: "music/VegetaPhonk.mp3" },
  { title: "Tevvez - Glimmer of Hope __ Domain of the Gods", file: "music/TevvezDomain.mp3" },
  { title: "fragment (slowed) - slxughter", file: "music/fragmentSlowed.mp3" },
  { title: "POOR - gqtis", file: "music/PoorGqtis.mp3" },
  { title: "SHOORVEER 3 - Rapperiya Baalam", file: "music/ShoorveerIII.mp3" },
];

// IRF
const irfSongs = [
  { title: "Irfan - Jhol | Coke Studio Pakistan", file: "music/JholMannu.mp3" },
  { title: "Irfan - Aaryan shah - Isolation", file: "music/IsolationAaryan.mp3" },
  { title: "Irfan - G-Eazy & Halsey - Him & I", file: "music/Him&I.mp3" },
  { title: "Irfan - NOW OR NEVER - CXSPER", file: "music/NowOrNever.mp3" },
  { title: "Irfan - Tick Tick Boom - Sage", file: "music/TickTickBoom.mp3" },
  { title: "Irfan - Too Easy - Connor Price", file: "music/TooEasy.mp3" },
  { title: "Shantanu - Don't Stay - Linkin Park", file: "music/DontStayLinkin.mp3" },
  { title: "Shantanu - In The End - Linkin Park", file: "music/InTheEndLinkin.mp3" },
  { title: "Shantanu - New Divide - Linkin Park", file: "music/NewDivideLinkin.mp3" },
  { title: "Shantanu - Numb _ Encore - Linkin Park _ JAY-Z", file: "music/NumbEncoreLinkin.mp3" },
  { title: "Shantanu - What I've Done - Linkin Park", file: "music/WhatILinkin.mp3" },
  { title: "Shantanu - Dopamine - Youth (Official Audio)", file: "music/DopamineYouth.mp3" },
  { title: "Shantanu - John Wick Reckoning", file: "music/JohnWickReckoning.mp3" },
  { title: "Shantanu - MGK - Invincible (Explicit) ft. Ester Dean", file: "music/MGKInvincible.mp3" },
  { title: "Shantanu - Panjabi MC - Jogi (Official Video)", file: "music/PanjabiMC.mp3" },
  { title: "Shantanu - Shoot Da Order Sukha Kahlon", file: "music/ShootDaSukha.mp3" },
];

// RAP
const rapSongs = [
  { title: "JDM - Bhaskar", file: "music/JDMBhaskar.mp3" },
  { title: "Lachak - Bhaskar", file: "music/LachakBhaskar.mp3" },
  { title: "Dainik Bhaskar - Bhaskar", file: "music/DainikBhaskar.mp3" },
  { title: "Champions - Seedhe Maut", file: "music/ChampionsSeedhe.mp3" },
  { title: "Introduction - Farish Shafi", file: "music/IntroductionFaris.mp3" },
  { title: "Raat Ki Rani - Seedhe Maut", file: "music/RaatKiRaniSeedhe.mp3" },
  { title: "Dalli - Bhaskar", file: "music/Dalli.mp3" },
];

//Calm
const calmSongs = [
  {title:"Who Knows - Yo Yo Honey Singh % SODEE", file:"music/WhoKnows.mp3"},
  {title:"AMBARSARIYA", file:"music/AMBARSARIYA.mp3"},
  {title:"Care Ni Karda - Yo Yo Honey Singh", file:"music/CareNiKarda.mp3"},
  {title:"Kalaastar - Yo Yo Honey Singh", file:"music/Kalaastar.mp3"},
  {title:"Laungda Lashkara", file:"music/LaungdaLashkara.mp3"},
  {title:"Saibo", file:"music/Saibo.mp3"},
  {title:"Ajnabi - Atif Aslam", file:"music/AjnabiAtif.mp3"},
  {title:"BLUE EYES - Yo Yo Honey Singh", file:"music/BLUE_EYES.mp3"},
  {title:"Insane - AP Dhillon", file:"music/Insane.mp3"},
  {title:"Jal Pari - Atif Aslam", file:"music/JalPari.mp3"},
  {title:"Pehli Nazar Mein - Atif Aslam", file:"music/PehliNazarMein.mp3"},
  {title:"BANJAREY - Yo Yo Honey Singh", file:"music/BANJAREY.mp3"},
  {title:"Calm Down - Rema x Selena Gomez", file:"music/CalmDown.mp3"},
  {title:"Ghana Kasoota", file:"music/GhanaKasoota.mp3"},
  {title:"Mann Mera - Gajendra Verma", file:"music/MannMera.mp3"},
  {title:"Saiyaan Ji - Yo Yo Honey Singh", file:"music/SaiyaanJi.mp3"},
  {title:"Black Life", file:"music/Black Life.mp3"},
  {title:"Chidiya", file:"music/Chidiya.mp3"},
  {title:"Chori Chori", file:"music/Chori Chori.mp3"},
  {title:"Desi Kalakaar", file:"music/Desi Kalakaar.mp3"},
  {title:"Dil Diyan Gallan", file:"music/Dil Diyan Gallan.mp3"},
  {title:"Goosebumps (Remix)", file:"music/Goosebumps (Remix).mp3"},
  {title:"Pardes Katenda", file:"music/Pardes Katenda.mp3"},
  {title:"SAADI GALLI AAJA", file:"music/SAADI GALLI AAJA.mp3"},
  {title:"Savan", file:"music/Savan.mp3"},
  {title:"We Rollin", file:"music/We Rollin.mp3"},
]

//Ramzan Songs
const ramzanSongs = [{title:"Maula Ya Salli - Urdu", file:"music/MaulaYaSalli.mp3"},
  {title:"Muhammad Nabina - Nadah Si", file:"music/MuhammadNabina.mp3"},
  {title:"Allah Hu Allah Hu", file:"music/Allah Hu Allah Hu.mp3"},
  {title:"Mustafa Jaan E Rehmat Pe Lakhon Salam Naat Feat. Atif Aslam", file:"music/Mustafa Jaan E Rehmat Pe Lakhon Salam Naat Feat. Atif Aslam.mp3"},
  {title:"Coke Studio Season 8 Tajdar-e-Haram Atif Aslam", file:"music/Coke Studio Season 8 Tajdar-e-Haram Atif Aslam.mp3"},
  {title:"Coke Studio Season 12 Wohi Khuda Hai Atif Aslam", file:"music/Coke Studio Season 12 Wohi Khuda Hai Atif Aslam.mp3"},
  {title:"Faslon Ko Takalluf Hai", file:"music/Faslon Ko Takalluf Hai.mp3"},
  {title:"Kalimataan Nasheed - Subhan Allahi wa-bi hamdihi Subhan Allahi-l-Adheem", file:"music/Kalimataan Nasheed - Subhan Allahi wa-bi hamdihi Subhan Allahi-l-Adheem.mp3"},
  {title:"Maher Zain - Ya Nabi Salam Alayka (Arabic) ماهر زين - يا نبي سلام عليك", file:"music/Maher Zain - Ya Nabi Salam Alayka (Arabic) ماهر زين - يا نبي سلام عليك.mp3"},
  // {title:"Faslon Ko Takalluf Hai", file:"music/Faslon Ko Takalluf Hai.mp3"},
  {title:"Mesut Kurtis - Burdah Maula ya Salli مسعود كرتس البردة مولاي صل وسلم", file:"music/Mesut Kurtis - Burdah Maula ya Salli مسعود كرتس البردة مولاي صل وسلم.mp3"},
  // {title:"Mustafa Jaan E Rehmat Pe Lakhon Salam Naat Feat. Atif Aslam", file:"music/Mustafa Jaan E Rehmat Pe Lakhon Salam Naat Feat. Atif Aslam.mp3"},
  {title:"Nasheed - Tabalagh bil qaleel (sped up)", file:"music/Nasheed - Tabalagh bil qaleel (sped up).mp3"},
  {title:"taweel al shawq [ahmed bukhatir] sped up", file:"music/taweel al shawq [ahmed bukhatir] sped up.mp3"},
]

const sadSongs = [{title:"Tera Mera Rishta", file:"music/TeraMeraRishta.mp3"},
  {title:"Toh Phir Aao", file:"music/TohPhirAao.mp3"},
  {title:"Aye Khuda - Mithoon", file:"music/AyeKhudaMithoon.mp3"},
  {title:"Beete Lamhein - KK", file:"music/BeeteLamheinKK.mp3"},
  {title:"Dil Ke Arman - Salma Agha", file:"music/DilKeArman.mp3"},
  {title:"Tere Bin - Atif Aslam", file:"music/TereBinAtifAslam.mp3"},
  {title:"Doorie - Atif Aslam", file:"music/Doorie.mp3"},
  {title:"drunk text me - Lexi Jayde", file:"music/drunktextmeLexiJayde.mp3"},
  {title:"MAINE MERE JANA (Emptiness Female Version)", file:"music/MAINEMEREJANA.mp3"},
  {title:"Maine Royaan - Tanveer Evan", file:"music/MaineRoyaanTanveerEvan.mp3"},
  {title:"Maula - Ali Azmat", file:"music/MaulaAliAzmat.mp3"},
  {title:"Pani Da Rang - Ayushmann", file:"music/PaniDaRangAyushmann.mp3"},
  {title:"Phir Mohabbat", file:"music/PhirMohabbat.mp3"},
  {title:"Tu hai kahan Female - Shuddhi.mp3", file:"music/TuhaikahanFemaleShuddhi.mp3"},
  {title:"Tu Hai Kahan - AUR", file:"music/TuHaiKahanAUR.mp3"},
  {title:"Tune Jo Na Kaha", file:"music/TuneJoNaKaha.mp3"},
  {title:"Tune Mere Jana - Gajendra Verma", file:"music/Tune Mere Jana - Gajendra Verma.mp3"},
  {title:"Aadat (From Kalyug) - Atif Aslam", file:"music/Aadat (From Kalyug) - Atif Aslam.mp3"},
  {title:"Afusic - Pal Pal with @Talwiinder", file:"music/Afusic - Pal Pal with @Talwiinder.mp3"},
  {title:"Bang Bang (My Baby Shot Me Down) (FromKill Bill)", file:"music/Bang Bang (My Baby Shot Me Down) (FromKill Bill) - Geek Music.mp3"},
  {title:"EK RAAT X ISHQ NACHAAWE - ZAEN MASHUP", file:"music/EK RAAT X ISHQ NACHAAWE - ZAEN MASHUP - ZAEN MUSIC.mp3"},
  {title:"Hum Jee Lenge Mustafa Zahid, Roxen Band", file:"music/Hum Jee Lenge Mustafa Zahid, Roxen Band.mp3"},
  {title:"Husn - Anuv Jain", file:"music/Husn - Anuv Jain.mp3"},
  {title:"Jo Tum Mere Ho - Anuv Jain", file:"music/Jo Tum Mere Ho - Anuv Jain.mp3"},
  {title:"Judai - Pritam", file:"music/Judai - Pritam.mp3"},
  {title:"Koi Si - Afsana Khan", file:"music/Koi Si - Afsana Khan.mp3"},
  {title:"Kuch Is Tarah - Atif Aslam", file:"music/Kuch Is Tarah - Atif Aslam.mp3"},
  {title:"Maand - Bayaan (female acoustic) - Shruti Shrivastava", file:"music/Maand - Bayaan (female acoustic) - Shruti Shrivastava.mp3"},
  // {title:"Main Khuda Ko Bataunga.mp3", file:"music/Main Khuda Ko Bataunga.mp3"},
  {title:"Mausam - Mithoon", file:"music/Mausam - Mithoon.mp3"},
  {title:"mausam x kabira x teri meri mashup - Ab6 music.mp3", file:"music/mausam x kabira x teri meri song editing mashup slowed hindi - Ab6 music.mp3"},
  {title:"TERI YAADON MEIN - KK.mp3", file:"music/TERI YAADON MEIN - KK.mp3"},
  {title:"Yeh Jism - Ali Azmat", file:"music/Yeh Jism - Ali Azmat.mp3"},
]

const healSongs = [
  {title:"Ek Raat - VILEN", file:"music/Ek Raat.mp3"},
  {title:"I'M Done", file:"music/I'M Done.mp3"},
  {title:"Tera Ghata", file:"music/Tera Ghata.mp3"},
  {title:"Todh", file:"music/Todh.mp3"},
  {title:"Tujhko Kya Fikar_", file:"music/Tujhko Kya Fikar_.mp3"},
  {title:"Victory Anthem", file:"music/Victory Anthem.mp3"},
  {title:"WORTH NOTHING - PHONK", file:"music/WORTH NOTHING - PHONK.mp3"},
  {title:"Yaad Na Aaye", file:"music/Yaad Na Aaye.mp3"},
]

const shantanuSongs = [
    { title: "Shantanu - Don't Stay - Linkin Park", file: "music/DontStayLinkin.mp3" },
  { title: "Shantanu - In The End - Linkin Park", file: "music/InTheEndLinkin.mp3" },
  { title: "Shantanu - New Divide - Linkin Park", file: "music/NewDivideLinkin.mp3" },
  { title: "Shantanu - Numb _ Encore - Linkin Park _ JAY-Z", file: "music/NumbEncoreLinkin.mp3" },
  { title: "Shantanu - What I've Done - Linkin Park", file: "music/WhatILinkin.mp3" },
  { title: "Shantanu - Dopamine - Youth (Official Audio)", file: "music/DopamineYouth.mp3" },
  { title: "Shantanu - John Wick Reckoning", file: "music/JohnWickReckoning.mp3" },
  { title: "Shantanu - MGK - Invincible (Explicit) ft. Ester Dean", file: "music/MGKInvincible.mp3" },
  { title: "Shantanu - Panjabi MC - Jogi (Official Video)", file: "music/PanjabiMC.mp3" },
  { title: "Shantanu - Shoot Da Order Sukha Kahlon", file: "music/ShootDaSukha.mp3" },
  { title: "Shantanu - Arey Pagol Hoye Jabo Ami _ Deep Jandu _ Bohemia", file: "music/Arey Pagol Hoye Jabo Ami _ Deep Jandu _ Bohemia.mp3" },
  { title: "Shantanu - Brothers Osborne - Skeletons (Official Music Video)", file: "music/Brothers Osborne - Skeletons (Official Music Video).mp3" },
  { title: "Shantanu - Hukum - Hindi (From _Rajini The Jailer_)", file: "music/Hukum - Hindi (From _Rajini The Jailer_).mp3" },
  { title: "Shantanu - Hukum Reloaded - Hindi (From _Rajini The Jailer 2_)", file: "music/Hukum Reloaded - Hindi (From _Rajini The Jailer 2_).mp3" },
  { title: "Shantanu - Jaguar _ Muzical Doctorz Sukhe Feat Bohemia _ Latest Punjabi Songs _ Speed Records.mp3", file: "music/Jaguar _ Muzical Doctorz Sukhe Feat Bohemia _ Latest Punjabi Songs _ Speed Records.mp3" },
  { title: "Shantanu - Linkin Park & Steve Aoki - A Light That Never Comes (Extended)", file: "music/Linkin Park & Steve Aoki - A Light That Never Comes (Extended).mp3" },
  { title: "Shantanu - Toh Phir Aao (Remix)", file: "music/Toh Phir Aao (Remix).mp3" },
  { title: "Shantanu - _Raftaarein_ Ra.One _ Shahrukh Khan, Kareena Kapoor", file: "music/RaftareinRaOne.mp3" },
  { title: "Shantanu - 12 SAAL - BILAL SAEED", file: "music/12 SAAL - BILAL SAEED - OFFICIAL VIDEO HD.mp3" },
  { title: "Shantanu - Arjan Vailly", file: "music/Arjan Vailly.mp3" },
  { title: "Shantanu - Banke Tera Jogi - Phir Bhi Dil Hai Hindustani_Shah Rukh Khan, Juhi_Alka Yagnik", file: "music/Banke Tera Jogi Full Video - Phir Bhi Dil Hai Hindustani_Shah Rukh Khan, Juhi_Alka Yagnik.mp3" },
  { title: "Shantanu - Halamithi Habibo (Hindi) - Video Song _ Beast _ Thalapathy Vijay _ Sun Pictures _ Nelson _ Anirudh", file: "music/Halamithi Habibo (Hindi) - Video Song _ Beast _ Thalapathy Vijay _ Sun Pictures _ Nelson _ Anirudh.mp3" },
  { title: "Shantanu - Ishq Jalakar - Karvaan (From _Dhurandhar_) · Shashwat Sachdev · Irshad Kamil", file: "music/Ishq Jalakar - Karvaan (From _Dhurandhar_) · Shashwat Sachdev · Irshad Kamil .mp3" },
  { title: "Shantanu - Kya Mujhe Pyaar Hai (Official Remix)", file: "music/Kya Mujhe Pyaar Hai (Official Remix).mp3" },
  { title: "Shantanu - Linkin Park - Lost In The Echo (Extended)", file: "music/Linkin Park - Lost In The Echo (Extended).mp3" },
  { title: "Shantanu - Aao Milo Chalen_ Jab We Met_ Shahid Kapoor,Kareena Kapoor_ Pritam, Shaan, Ustad Sultan Khan", file: "music/Lyrical_ Aao Milo Chalen_ Jab We Met_ Shahid Kapoor,Kareena Kapoor_ Pritam, Shaan, Ustad Sultan Khan.mp3" },
  { title: "Shantanu - Na Kajre Ki Dhar _ Lyrics _ Suniel Shetty _ Pankaj Udhas & Sadhana Sargam", file: "music/Na Kajre Ki Dhar _ Lyrics _ Suniel Shetty _ Pankaj Udhas & Sadhana Sargam.mp3" },
  { title: "Shantanu - 8 ASLE - SUKHA _ GURLEZ AKHTAR _ CHANI NATTAN _ PRODGK", file: "music/8 ASLE - SUKHA _ GURLEZ AKHTAR _ CHANI NATTAN _ PRODGK.mp3" },
  { title: "Shantanu - Bhaag Milkha Bhaag (Rock Version)", file: "music/Bhaag Milkha Bhaag (Rock Version).mp3" },
  { title: "Shantanu - Brothers Anthem - Brothers _ Akshay Kumar _ Sidharth Malhotra", file: "music/Brothers Anthem Lyric Video - Brothers _ Akshay Kumar _ Sidharth Malhotra.mp3" },
  { title: "Shantanu - Har Kisi Ko Nahi Milta Lyrics _ Boss _ Arijit Singh", file: "music/Har Kisi Ko Nahi Milta Lyrics _ Boss _ Arijit Singh, Neeti Mohan _ Akshay Kumar, Sonakshi Sinha _.mp3" },
  { title: "Shantanu - Kangna _ Dr Zeus _ Master Rakesh", file: "music/Kangna _ Dr Zeus _ Master Rakesh _ Audio _ Unda Da Influence _ Punjabi Song.mp3" },
  { title: "Shantanu - Kevin Rudolf - Let It Rock ft. Lil Wayne", file: "music/Kevin Rudolf - Let It Rock ft. Lil Wayne (Official Music Video).mp3" },
  { title: "Shantanu - Kurbaan Hua - Audio Song _ Kareena Kapoor, Saif Ali Khan", file: "music/Kurbaan Hua - Audio Song _ Kareena Kapoor, Saif Ali Khan _ Vishal Dadlani _ Salim-Sulaiman.mp3" },
  { title: "Shantanu -  Chand Sifarish Song with Fanaa", file: "music/Lyrical _ Chand Sifarish Song with Lyrics _ Fanaa _ Aamir Khan _ Kajol _ Jatin-Lalit _ Prasoon Joshi.mp3" },
  { title: "Shantanu -  Sadda Haq _ Rockstar _ Ranbir Kapoor _ Mohit Chauhan _ A.R. Rahman", file: "music/Lyrical _ Sadda Haq Video Song  _ Rockstar _ Ranbir Kapoor _ Mohit Chauhan _ A.R. Rahman.mp3" },
  { title: "Shantanu -  Kaise Mujhe _ Ghajini _ Aamir Khan, Asin _ Benny Dayal, Shreya Ghosal _ A.R. Rahman", file: "music/LYRICAL_ Kaise Mujhe _ Ghajini _ Aamir Khan, Asin _ Benny Dayal, Shreya Ghosal _ A.R. Rahman.mp3" },
  
  
]

// MASTER PLAYLIST (flattened for player controls)
const playlist = [
  ...energyPhonk,
  ...irfSongs,
  ...rapSongs,
  ...calmSongs,
  ...ramzanSongs,
  ...sadSongs,
  ...healSongs,
  ...shantanuSongs
];
