const playlist = [
    { title: "Sunny Sunny", file: "music/SunnySunny.mp3",category: "Energy/Phonk" },
  { title: "Against All Odds AP Dhillon", file: "music/AgainstAllOdds.mp3",category: "Energy/Phonk" },
  { title: "Gigachad Theme", file: "music/gigachad.mp3",category: "Energy/Phonk" },
  { title: "Metamorphosis Interworld", file: "music/metamorphosis.mp3",category: "Energy/Phonk" },
  { title: "Sahara Hensonn", file: "music/saharahensonn.mp3",category: "Energy/Phonk" },
  { title: "Crystals Isolate", file: "music/crystalsIsolate.mp3",category: "Energy/Phonk" },
    { title: "Jhol | Coke Studio Pakistan | Season 15", file: "music/JholMannu.mp3",category: "IRF" },
  { title: "Aaryan shah -Isolation", file: "music/IsolationAaryan.mp3",category: "IRF" },
  { title: "G-Eazy & Halsey - Him & I", file: "music/Him&I.mp3",category: "IRF" },
  { title: "JDM - Bhaskar", file: "music/JDMBhaskar.mp3",category: "Rap" },
  { title: "Lachak - Bhaskar", file: "music/LachakBhaskar.mp3",category: "Rap" },
  { title: "Dainik Bhaskar - Bhaskar", file: "music/DainikBhaskar.mp3",category: "Rap" },
  { title: "Aarambh Prachand X Polezehnie", file: "music/AarambhPrachandPolo.mp3",category: "Energy/Phonk" },
];
